import { Cherry_Bomb_One, Itim } from "next/font/google";
import "./globals.css";
import Navbar from '@/app/components/Navbar.js'
import Footer from '@/app/components/Footer.js'

const CBOfont = Cherry_Bomb_One({
  variable: "--font-cbo",
  subsets:["latin"],
  weight:"400",
})


const itimFont = Itim({
  variable: "--font-itim",
  subsets: ["latin"],
  weight: "400",
}
)

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${itimFont.variable} ${CBOfont.variable} antialiased`}
      >
        <Navbar title="Jason's recipes" year={2025}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
